# Generated by Django 3.0.6 on 2020-05-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Vendors')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50)),
                ('avg_price', models.IntegerField()),
                ('desc', models.TextField()),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.VendorType')),
            ],
        ),
    ]
